name: Build and Push Docker Images

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Model Docker image
        run: |
          docker build \
          -t '${{secrets.DOCKER_LOGIN}}'/treasury-tracker-model:'latest'  ./model

      - name: Build the Backend Docker image
        run: |
          docker build -t '${{secrets.DOCKER_LOGIN}}'/treasury-tracker-backend:'latest'  ./backend

      # Login to Docker Hub
      - name: Login to Docker Hub
        run: |
          docker login --username '${{secrets.DOCKER_LOGIN}}' --password '${{secrets.DOCKER_PASSWORD}}'

      - name: Push the Backend Docker image
        run: |
          docker push '${{secrets.DOCKER_LOGIN}}'/treasury-tracker-backend:latest

      - name: Push the Model Docker image
        run: |
          docker push '${{secrets.DOCKER_LOGIN}}'/treasury-tracker-model:latest
            
  ssh_update:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_SSH_KEY}}
          port: 22
          script: |
            sudo docker login -u "${{secrets.DOCKER_LOGIN}}" -p "${{secrets.DOCKER_PASSWORD}}"
            sudo docker pull '${{secrets.DOCKER_LOGIN}}'/treasury-tracker-backend:latest
            sudo docker pull '${{secrets.DOCKER_LOGIN}}'/treasury-tracker-model:latest
            sudo docker stop treasury-tracker-backend || true
            sudo docker rm treasury-tracker-backend || true
            sudo docker stop treasury-tracker-model || true
            sudo docker rm treasury-tracker-model || true
            sudo docker run -d --name treasury-tracker-backend -p 5000:5000 '${{secrets.DOCKER_LOGIN}}'/treasury-tracker-backend:latest
            sudo docker run -d --name treasury-tracker-model -p 5500:5000 '${{secrets.DOCKER_LOGIN}}'/treasury-tracker-backend:latest